### ISSUE TITLE
一个 PG 高性能全文搜索扩展.  pgroonga 以及其依赖包 groonga

### ISSUE THREAD

**Issue by zw963** [taotieren/aur-repo#6]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

一个 PG 高性能全文搜索扩展, 挺好用的, 来自日本开发者, 亲测对中文全文搜索有很好的支持, 难得.

https://pgroonga.github.io/

[开发者 tuturial](https://pgroonga.github.io/tutorial)

* 主要语言和工具链 / Main Languages and Toolchains

   postgresql llvm

* 上游链接 / Upstream Link

https://aur.archlinux.org/pkgbase/groonga.git
https://aur.archlinux.org/pgroonga.git

* 为何需要这个软件包 / Why Need This Package

https://groonga.org/docs/install.html

官方支持大部分 VPS 上的常见系统包管理快捷安装, 但是, Arch 本地开发就有点麻烦了,作为一个 pg 数据库的扩展, 安装起来的确挺麻烦.

下面是个人修改后的 PKGBUILD, 更新了版本, 也删除了几个不需要的依赖(日文高精度搜索, 以及 Ruby 依赖), 因为我发现即使不安装 Ruby 依赖, 仍然可以使用 Ruby 的正则表达式.

[groonga](https://github.com/taotieren/aur-repo/files/15048623/PKGBUILD.gz)
[pgroonga](https://github.com/taotieren/aur-repo/files/15048626/PKGBUILD.gz)

**Comment by taotieren** [comment]
已添加： https://github.com/taotieren/aur-repo/commit/45b1cced3fcfdcacf6104387e61fc7bd276a273b
